[package]
name = "gazpacho-compile"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
gazpacho-datatypes = { path = "../gazpacho-datatypes" }
gazpacho-ast = { path = "../gazpacho-ast" }
gazpacho-operations = { path = "../gazpacho-operations" }
eyre.workspace = true

[lints]
workspace = true
