[package]
name = "gazpacho-ast"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
num-rational.workspace = true
gazpacho-datatypes = { path = "../gazpacho-datatypes" }

[dev-dependencies]
eyre.workspace = true
