[package]
name = "gazpacho-render"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[features]
serde = ["dep:serde", "gazpacho-datatypes/serde"]

[dependencies]
eyre.workspace = true
tracing.workspace = true
serde = { workspace = true, optional = true, features = ["derive"] }
gazpacho-datatypes = { path = "../gazpacho-datatypes" }
gazpacho-ast = { path = "../gazpacho-ast" }
gazpacho-compile = { path = "../gazpacho-compile" }
gazpacho-media = { path = "../gazpacho-media" }
gazpacho-operations = { path = "../gazpacho-operations" }

[dev-dependencies]
tracing-subscriber.workspace = true
gazpacho-ast = { path = "../gazpacho-ast" }

[lints]
workspace = true
