[package]
name = "gazpacho-operations"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
eyre.workspace = true
bitflags = "2.13.1"
gazpacho-datatypes = { path = "../gazpacho-datatypes" }
rapidhash = "4.5.1"


[lints]
workspace = true
