[package]
name = "gazpacho-datatypes"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
num-traits.workspace = true
num-rational.workspace = true
ordered-float = "5.5.0"
string-interner = "0.20.0"

[lints]
workspace = true
