[package]
name = "gazpacho-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
color-eyre.workspace = true
ffmpeg-sidecar.workspace = true
itertools.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true
phf = { workspace = true, features = ["macros"] }
ron.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
